'use client'

import './globals.css'
import {
  useQuery,
  useMutation,
  useQueryClient,
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  
  const queryClient = new QueryClient()
  
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
      <body>
        {children}
      </body>
      </QueryClientProvider>
    </html>
  )
}
